name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: salon
        host: 164.52.212.187
        key: ${{ secrets.SSH_PASSWORD }}
        passphrase: salon@2022
        script: 'cd /home/salon/public_html/salonnew && bash ./server_deploy.sh'